<a href="https://colab.research.google.com/github/dinukaattanayaka/ML-Multi-variable-Linear-Regression-heart-risk-prediction-regression-model-/blob/main/ML_heart_risk_prediction_regression_model(Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('/content/drive/MyDrive/machine learning/DAY 6 (Regression)/cardio_dataset.csv').values
print(dataset, dataset.shape)


[[  1.   48.  236.  ...   1.    0.    1.1]
 [  0.   48.  260.  ...   1.    1.    7. ]
 [  0.   44.  187.  ...   1.    0.    7. ]
 ...
 [  0.   65.  212.  ...   0.    0.   30.6]
 [  0.   66.  184.  ...   0.    0.   23.8]
 [  1.   45.  203.  ...   1.    0.    1. ]] (6644, 8)


In [5]:
data=dataset[:,0:7]
target=dataset[:,7]

print(data, data.shape)
print(target, target.shape)

[[  1.  48. 236. ...   0.   1.   0.]
 [  0.  48. 260. ...   0.   1.   1.]
 [  0.  44. 187. ...   1.   1.   0.]
 ...
 [  0.  65. 212. ...   1.   0.   0.]
 [  0.  66. 184. ...   0.   0.   0.]
 [  1.  45. 203. ...   0.   1.   0.]] (6644, 7)
[ 1.1  7.   7.  ... 30.6 23.8  1. ] (6644,)


In [6]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [7]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [8]:
print('coef:',model.coef_)
print('a0:',model.intercept_)

coef: [-4.89328798  0.73200038  0.02500329 -0.07112129  5.79670853 -5.20785598
 10.87256666]
a0: -27.56724101808443


In [9]:
print('Actaul:',test_target[:10])
print('Predicted:',predicted_target[:10])

Actaul: [13.   5.6  0.7 36.2 13.4 26.   3.8 10.6  1.5  1.7]
Predicted: [24.78684089 12.12056292 -0.50811807 25.01647409 15.98093375 20.63360207
  7.11023816 16.3812568   4.80056285  3.31033522]


In [10]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print('r2:',r2)        #r2 value eka 1 ta lan weddi hodai

r2: 0.7665971908903398


In [11]:
import joblib

joblib.dump(model,'/content/drive/MyDrive/machine learning/DAY 6 (Regression)/ML heart risk prediction regression model(my).sav')

['/content/drive/MyDrive/machine learning/DAY 6 (Regression)/ML heart risk prediction regression model(my).sav']